### PR TITLE
if returns now valid value in every case

### PR DESCRIPTION
**Pull request by Torpheus**
support define without initialization, and if without else

### CODE REVIEW

**Comment by rapgru** [comment]
Why did you decide against the `Maybe` datatype?

**Comment by Torpheus** [comment]
While the specification does not specify which value is returned by a if expression without else branch when the condition is #f, it is necessary that some value is returned. This can be as correct and more easily achieved if the parser just adds an else branch which returns #f in case the user specifies non.

**Comment by rapgru** [comment]
I shall quote the standard: 
> If〈test〉yields a false value and no〈alternate〉isspecified, then the result of the expression is unspecified.

**Comment by Torpheus** [comment]
The standard further elaborates on the concept of unspecified:
`If  the  value  of  an  expression  is  said  to  be  “unspecified,”then the expression must evaluate to some object without signaling  an  error,  but  the  value  depends  on  the  implementation;  this report explicitly does not say what value is returned.`
This means that any object is fine as result of such a special if, #f in our case

**Comment by rapgru** [comment]
For Metamorph, we have mostly settled on using the `dyntype_t SCHEME_UNSPECIFIED` for unspecified results - partly to keep users from making assertions on unspecified results. I think it would be cleaner to uniformly continue this scheme.

**Comment by Torpheus** [comment]
If it is wished to represent every object who's value is unspecified trough an object of type unspecified, we should provide an Metanode Atom of such type, which will than be correctly handled and translated via the semantic analysis and the integrator.

**Comment by rapgru** [comment]
I'd say this is an exercise of the code generation / integration, because return types are not really handled by the analysis or parser. There is no Scheme representation for the special unspecified datatype so it cannot be produced in the scanner or parser. How would a `UnspecifiedAtom'` be useful for the return type of `set!` for example?

**Review by rapgru — APPROVED** [review]

**Pull request merged**
